-------------------------------------------------- Generator --------------------------------------------------
Existing cases: dict_keys([])
64 cases, 8 full circuits to run : [(2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9), (6, 10), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (7, 10), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (8, 9), (8, 10), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9), (9, 10)]
**************************************************
Generating 1x3, 1+8+1 supremacy circuit
3 qubit circuit saturated shots = 7168, ΔH = 3.370e-04
Evaluating fc state vector
Evaluating fc qasm, 7168 shots
Evaluating fc hardware, 7168 shots
Submitted 1 reps * 7168 shots to hardware, job_id = 5e099e83a36a9400121477fb
/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/qiskit/providers/models/backendconfiguration.py:337: UserWarning: `dt` and `dtm` now have units of seconds(s) rather than nanoseconds(ns).
  warnings.warn('`dt` and `dtm` now have units of seconds(s) rather '
Submitted measurement filter, 8 calibration circuits * 8192 shots, job_id = 5e099e84ee2824001150c4ff
**************************************************
Generating 2x2, 1+8+1 supremacy circuit
4 qubit circuit saturated shots = 10240, ΔH = 8.692e-04
Evaluating fc state vector
Evaluating fc qasm, 10240 shots
Evaluating fc hardware, 10240 shots
Submitted 2 reps * 5120 shots to hardware, job_id = 5e099e8606766d001137b5ad
Submitted measurement filter, 16 calibration circuits * 8192 shots, job_id = 5e099e88b548320011260008
**************************************************
Generating 1x5, 1+8+1 supremacy circuit
5 qubit circuit saturated shots = 16384, ΔH = 9.580e-04
Evaluating fc state vector
Evaluating fc qasm, 16384 shots
Evaluating fc hardware, 16384 shots
Submitted 2 reps * 8192 shots to hardware, job_id = 5e099e8ba36a9400121477fc
Submitted measurement filter, 32 calibration circuits * 8192 shots, job_id = 5e099e8cee2824001150c500
**************************************************
Generating 3x2, 1+8+1 supremacy circuit
6 qubit circuit saturated shots = 35840, ΔH = 9.879e-04
Evaluating fc state vector
Evaluating fc qasm, 35840 shots
Evaluating fc hardware, 35840 shots
Submitted 5 reps * 7168 shots to hardware, job_id = 5e099e9039e98100125549ba
Submitted measurement filter, 64 calibration circuits * 8192 shots, job_id = 5e099e93e7977f001127c7fb
**************************************************
Generating 1x7, 1+8+1 supremacy circuit
7 qubit circuit saturated shots = 74752, ΔH = 9.851e-04
Evaluating fc state vector
Evaluating fc qasm, 74752 shots
Evaluating fc hardware, 74752 shots
Submitted 73 reps * 1024 shots to hardware, job_id = 5e099e9a5879b80012ec7618
Submitted measurement filter, 128 calibration circuits * 8192 shots, job_id = 5e099e9d39e98100125549bc
**************************************************
Generating 2x4, 1+8+1 supremacy circuit
8 qubit circuit saturated shots = 121856, ΔH = 1.021e-03
Evaluating fc state vector
Evaluating fc qasm, 121856 shots
Evaluating fc hardware, 121856 shots
Submitted 17 reps * 7168 shots to hardware, job_id = 5e099ea6b54832001126000b
Submitted measurement filter, 256 calibration circuits * 8192 shots, job_id = 5e099eaa06766d001137b5b2
**************************************************
Generating 3x3, 1+8+1 supremacy circuit
9 qubit circuit saturated shots = 256000, ΔH = 1.021e-03
Evaluating fc state vector
Evaluating fc qasm, 256000 shots
Evaluating fc hardware, 256000 shots
Submitted 50 reps * 5120 shots to hardware, job_id = 5e099ebdefb76e0011437b28
Submitted measurement filter, 512 calibration circuits * 8192 shots, job_id = 5e099ec4e7977f001127c803
**************************************************
Generating 2x5, 1+8+1 supremacy circuit
10 qubit circuit saturated shots = 514048, ΔH = 1.024e-03
Evaluating fc state vector
Evaluating fc qasm, 514048 shots
Evaluating fc hardware, 514048 shots
Submitted 251 reps * 2048 shots to hardware, job_id = 5e099ef07272e100112dd145
**************************************************
Retrieving 3-qubit circuit
Meas filter job id 5e099e84ee2824001150c4ff
job_id : 5e099e83a36a9400121477fb
Mitigation for 1 * 3 qubit circuit took 1.288e-02 seconds
**************************************************
Retrieving 4-qubit circuit
Meas filter job id 5e099e88b548320011260008
job_id : 5e099e8606766d001137b5ad
Mitigation for 2 * 4 qubit circuit took 1.689e-01 seconds
**************************************************
Retrieving 5-qubit circuit
Meas filter job id 5e099e8cee2824001150c500
job_id : 5e099e8ba36a9400121477fc
Mitigation for 2 * 5 qubit circuit took 1.792e-01 seconds
**************************************************
Retrieving 6-qubit circuit
Meas filter job id 5e099e93e7977f001127c7fb
job_id : 5e099e9039e98100125549ba
Mitigation for 5 * 6 qubit circuit took 2.207e-01 seconds
**************************************************
Retrieving 7-qubit circuit
Meas filter job id 5e099e9d39e98100125549bc
job_id : 5e099e9a5879b80012ec7618
Mitigation for 73 * 7 qubit circuit took 5.972e+00 seconds
**************************************************
Retrieving 8-qubit circuit
Meas filter job id 5e099eaa06766d001137b5b2
job_id : 5e099ea6b54832001126000b
Mitigation for 17 * 8 qubit circuit took 9.033e+00 seconds
**************************************************
Retrieving 9-qubit circuit
Meas filter job id 5e099ec4e7977f001127c803
job_id : 5e099ebdefb76e0011437b28
Traceback (most recent call last):
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/weit/circuit_cutting/hardware/generator.py", line 146, in <module>
    del full_circ_info[full_circ_size]['fc_evaluations']['meas_filter']
KeyError: 'meas_filter'
Mitigation for 50 * 9 qubit circuit took 1.555e+02 seconds
**************************************************
Retrieving 10-qubit circuit
job_id : 5e099ef07272e100112dd145
/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/qiskit/providers/models/backendconfiguration.py:337: UserWarning: `dt` and `dtm` now have units of seconds(s) rather than nanoseconds(ns).
  warnings.warn('`dt` and `dtm` now have units of seconds(s) rather '
-------------------------------------------------- Job Submittor --------------------------------------------------
Existing cases: dict_keys([])
Run cases: dict_keys([])
**************************************************
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/qiskit/providers/models/backendconfiguration.py:337: UserWarning: `dt` and `dtm` now have units of seconds(s) rather than nanoseconds(ns).
  warnings.warn('`dt` and `dtm` now have units of seconds(s) rather '
-------------------------------------------------- Job Submittor --------------------------------------------------
Existing cases: dict_keys([])
Run cases: dict_keys([])
**************************************************
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
-------------------------------------------------- Plot --------------------------------------------------
/home/weit/circuit_cutting/hardware/plot.py:39: UserWarning: Attempting to set identical left == right == -0.5 results in singular transformations; automatically expanding.
  im = ax.imshow(data, **kwargs)
/home/weit/circuit_cutting/hardware/plot.py:39: UserWarning: Attempting to set identical bottom == top == -0.5 results in singular transformations; automatically expanding.
  im = ax.imshow(data, **kwargs)
Traceback (most recent call last):
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/weit/circuit_cutting/hardware/plot.py", line 334, in <module>
    plot_fid_bar(saturated_best_cc=saturated_best_cc, sametotal_best_cc=sametotal_best_cc,circuit_type=args.circuit_type,dirname=dirname,device_name=args.device_name)
  File "/home/weit/circuit_cutting/hardware/plot.py", line 243, in plot_fid_bar
    plt.legend()
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2685, in legend
    return gca().legend(*args, **kwargs)
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 406, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/legend.py", line 575, in __init__
    self._init_legend_box(handles, labels, markerfirst)
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/legend.py", line 833, in _init_legend_box
    fontsize, handlebox))
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 115, in legend_artist
    fontsize, handlebox.get_transform())
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 299, in create_artists
    self.update_prop(p, orig_handle, legend)
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 72, in update_prop
    self._update_prop(legend_handle, orig_handle)
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 65, in _update_prop
    self._update_prop_func(legend_handle, orig_handle)
  File "/home/weit/anaconda3/envs/cc-env/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 38, in update_from_first_child
    tgt.update_from(src.get_children()[0])
IndexError: list index out of range
Processing ./hardware/benchmark_data/supremacy_ibmq_johannesburg/hw_plotter_input_ibmq_johannesburg_saturated.p
************************* Best Cases *************************
**************************************************
Processing ./hardware/benchmark_data/supremacy_ibmq_johannesburg/hw_plotter_input_ibmq_johannesburg_sametotal.p
************************* Best Cases *************************
**************************************************
