-------------------------------------------------- Generator --------------------------------------------------
Existing cases: dict_keys([])
Using license file /Users/weitang/gurobi.lic
Academic license - for non-commercial use only
********************
MIQCP stats:
6 cuts, 3 clusters, max qubit = 9
cluster 0: original input = 4.00, ρ_qubits = 3.00, O_qubits = 1.00, d = 7.00
cluster 1: original input = 8.00, ρ_qubits = 1.00, O_qubits = 3.00, d = 9.00
cluster 2: original input = 4.00, ρ_qubits = 2.00, O_qubits = 2.00, d = 6.00
objective value = 6.000e+00
manually calculated objective value: 1.134e+03
evaluator_cost = 1134, reconstructor_cost = 1.095e+00, reconstructor_weight = 0.000e+00
runtime: 0.4124319553375244
OPTIMAL
********************
Adding case (9, 16) to run
16 qubit circuit saturated shots = 163840, χ^2 = 1.877e-01
Adding 16 qubit full circuit to run, 163840 shots
----------------------------------------------------------------------------------------------------
1 cases, 1 full circuits to run : dict_keys([(9, 16)])
******************** Submitting jobs ********************
Submitting job 1/1 e1120c67-17ed-4e1c-a85b-60fea4680957 --> 1 circuits, 20 * 8192 shots
******************** Retrieving jobs ********************
Retrieving job 1/1 e1120c67-17ed-4e1c-a85b-60fea4680957 --> 1 circuits, 20 * 8192 shots
Case (9, 16) sv distance = 2.209e-31, hw distance = 1.894e-01
-------------------------------------------------- Evaluator --------------------------------------------------
Existing cases: dict_keys([])
Running case: (9, 16)
case (9, 16), cluster_0 7_qubits * 648_instances on ibmq_boeblingen QUANTUM HARDWARE
case (9, 16), cluster_1 6_qubits * 324_instances on ibmq_boeblingen QUANTUM HARDWARE
case (9, 16), cluster_2 9_qubits * 162_instances on ibmq_boeblingen QUANTUM HARDWARE
Rank MASTER dumped case (9, 16), 1/1 cases
----------------------------------------------------------------------------------------------------
-------------------------------------------------- Job Submittor --------------------------------------------------
Existing cases: dict_keys([])
Run cases: dict_keys([(9, 16)])
**************************************************
Case (9, 16)
Cluster 0 sametotal shots = 8192
Cluster 1 sametotal shots = 8192
Cluster 2 sametotal shots = 8192
******************** Submitting jobs ********************
Submitting job 1/2 3e76d294-5485-46c8-b9b4-43f122a0a886 --> 900 circuits, 900 * 8192 shots
Submitting job 2/2 bac8fa57-8395-4a17-8977-f9cac259f0a8 --> 234 circuits, 234 * 8192 shots
******************** Retrieving jobs ********************
Retrieving job 1/2 3e76d294-5485-46c8-b9b4-43f122a0a886 --> 900 circuits, 900 * 8192 shots
Retrieving job 2/2 bac8fa57-8395-4a17-8977-f9cac259f0a8 --> 234 circuits, 234 * 8192 shots
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Cut into  [7, 6, 9] clusters
prep took 0.18 seconds
reconstruction len =  65536 probabilities sum =  0.9999805507807196
Reconstruction took 14.62 seconds
reorder took 0.32 seconds
qasm metric = 1.877e-01
hw metric = 1.894e-01
cutting metric = 6.266e-02
Reconstruction output has 1 cases
----------------------------------------------------------------------------------------------------
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Cut into  [7, 6, 9] clusters
prep took 11.19 seconds
Reconstruction took 0.00 seconds
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Cut into  [7, 6, 9] clusters
prep took 10.90 seconds
65536
Reconstruction took 0.00 seconds
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Cut into  [7, 6, 9] clusters
prep took 11.19 seconds
Reconstruction took 2.77 seconds
reorder took 0.31 seconds
qasm metric = 1.877e-01
hw metric = 1.894e-01
cutting metric = 6.266e-02
Reconstruction output has 1 cases
----------------------------------------------------------------------------------------------------
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Traceback (most recent call last):
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/weitang/Documents/circuit_cutting/utils/reconstructor.py", line 334, in <module>
    reconstructed_prob = compute(reconstruction_terms)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function prod at 0x10ec14dd0>) with argument(s) of type(s): (list(int64))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function prod at 0x10ec14dd0>)
[2] During: typing of call at /Users/weitang/Documents/circuit_cutting/utils/reconstructor.py (284)


File "utils/reconstructor.py", line 284:
def compute(reconstruction_terms):
    reconstruction_length = np.prod([len(x) for x in reconstruction_terms[0]])
    ^

Cut into  [7, 6, 9] clusters
prep took 11.27 seconds
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/ir_utils.py:2041: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'reconstruction_terms' of function 'compute'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "utils/reconstructor.py", line 283:
@njit
def compute(reconstruction_terms,reconstruction_length):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
Traceback (most recent call last):
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/weitang/Documents/circuit_cutting/utils/reconstructor.py", line 334, in <module>
    reconstructed_prob = compute(reconstruction_terms,reconstruction_length)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler.py", line 331, in compile_extra
    return self._compile_bytecode()
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler.py", line 393, in _compile_bytecode
    return self._compile_core()
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler.py", line 373, in _compile_core
    raise e
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler.py", line 364, in _compile_core
    pm.run(self.state)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler_machinery.py", line 347, in run
    raise patched_exception
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/typed_passes.py", line 407, in run_pass
    NativeLowering().run_pass(state)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/typed_passes.py", line 351, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/lowering.py", line 302, in create_cpython_wrapper
    release_gil=release_gil)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/targets/cpu.py", line 162, in create_cpython_wrapper
    builder.build()
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/callwrapper.py", line 124, in build
    self.build_wrapper(api, builder, closure, args, kws)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/callwrapper.py", line 157, in build_wrapper
    val = cleanup_manager.add_arg(builder.load(obj), ty)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/callwrapper.py", line 60, in add_arg
    cleanup_arg()
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/callwrapper.py", line 42, in cleanup_arg
    self.api.reflect_native_value(ty, native.value, self.env_manager)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/pythonapi.py", line 1460, in reflect_native_value
    impl(typ, val, c)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/targets/boxing.py", line 760, in reflect_list
    raise TypeError(msg)
TypeError: Failed in nopython mode pipeline (step: nopython mode backend)
cannot reflect element of reflected container: reflected list(reflected list(array(float64, 1d, C)))

Cut into  [7, 6, 9] clusters
prep took 11.67 seconds
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Traceback (most recent call last):
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/weitang/Documents/circuit_cutting/utils/reconstructor.py", line 335, in <module>
    reconstructed_prob = compute(reconstruction_terms,reconstruction_length)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
[1] During: typing of argument at /Users/weitang/Documents/circuit_cutting/utils/reconstructor.py (285)

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstruction_length):
    reconstructed_prob = np.zeros(reconstruction_length)
    ^

This error may have been caused by the following argument(s):
- argument 0: Unsupported array dtype: object

Cut into  [7, 6, 9] clusters
prep took 11.57 seconds
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Traceback (most recent call last):
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/weitang/Documents/circuit_cutting/utils/reconstructor.py", line 334, in <module>
    reconstructed_prob = compute(reconstruction_terms,np.zeros(reconstruction_length))
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
[1] During: typing of argument at /Users/weitang/Documents/circuit_cutting/utils/reconstructor.py (285)

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstructed_prob):
    for term in reconstruction_terms:
    ^

This error may have been caused by the following argument(s):
- argument 0: Unsupported array dtype: object

Cut into  [7, 6, 9] clusters
prep took 11.15 seconds
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Cut into  [7, 6, 9] clusters
prep took 11.06 seconds
Reconstruction took 3.25 seconds
reorder took 0.32 seconds
qasm metric = 1.877e-01
hw metric = 1.894e-01
cutting metric = 6.266e-02
Reconstruction output has 1 cases
/Users/weitang/Documents/circuit_cutting/utils/reconstructor.py:283: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "compute" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at /Users/weitang/Documents/circuit_cutting/utils/reconstructor.py (285)

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstructed_prob):
    for term in reconstruction_terms:
    ^

  @jit
/Users/weitang/Documents/circuit_cutting/utils/reconstructor.py:283: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "compute" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstructed_prob):
    for term in reconstruction_terms:
    ^

  @jit
/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "compute" was compiled in object mode without forceobj=True, but has lifted loops.

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstructed_prob):
    for term in reconstruction_terms:
    ^

  state.func_ir.loc))
/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstructed_prob):
    for term in reconstruction_terms:
    ^

  state.func_ir.loc))
/Users/weitang/Documents/circuit_cutting/utils/reconstructor.py:283: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "compute" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at /Users/weitang/Documents/circuit_cutting/utils/reconstructor.py (285)

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstructed_prob):
    for term in reconstruction_terms:
    ^

  @jit
/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "compute" was compiled in object mode without forceobj=True.

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstructed_prob):
    for term in reconstruction_terms:
    ^

  state.func_ir.loc))
/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/numba/object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "utils/reconstructor.py", line 285:
def compute(reconstruction_terms,reconstructed_prob):
    for term in reconstruction_terms:
    ^

  state.func_ir.loc))
----------------------------------------------------------------------------------------------------
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/weitang/Documents/circuit_cutting/utils/reconstructor.py", line 344, in <module>
    reconstructed_prob = reverse_prob(prob_l=reconstructed_prob)
  File "/Users/weitang/Documents/circuit_cutting/utils/conversions.py", line 15, in reverse_prob
    reverse_prob_l[reverse_state] = p
ValueError: setting an array element with a sequence.
Cut into  [7, 6, 9] clusters
prep took 11.01 seconds
Reconstruction took 7.46 seconds
-------------------------------------------------- Reconstructor --------------------------------------------------
Existing cases: dict_keys([])
case (9, 16)
Cut into  [7, 6, 9] clusters
prep took 11.79 seconds
Reconstruction took 3.26 seconds
reorder took 0.33 seconds
qasm metric = 1.877e-01
hw metric = 1.894e-01
cutting metric = 6.266e-02
Reconstruction output has 1 cases
----------------------------------------------------------------------------------------------------
